Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # Vault1 VM
  config.vm.define "vault1" do |vault1|
    vault1.vm.hostname = "vault1"
    vault1.vm.network "private_network", ip: "192.168.56.130"  # Unique IP for vault1
    vault1.vm.provider :libvirt do |lv|
      lv.memory = 4096  # 4 GB of memory for vault1 VM
      lv.cpus = 2       # 2 CPUs for vault1 VM
    end
  end

  # Vault2 VM
  config.vm.define "vault2" do |vault2|
    vault2.vm.hostname = "vault2"
    vault2.vm.network "private_network", ip: "192.168.56.131"  # Unique IP for vault2
    vault2.vm.provider :libvirt do |lv|
      lv.memory = 4096  # 4 GB of memory for vault2 VM
      lv.cpus = 2       # 2 CPUs for vault2 VM
    end
  end

  # Vault3 VM
  config.vm.define "vault3" do |vault3|
    vault3.vm.hostname = "vault3"
    vault3.vm.network "private_network", ip: "192.168.56.132"  # Unique IP for vault3
    vault3.vm.provider :libvirt do |lv|
      lv.memory = 4096  # 4 GB of memory for vault3 VM
      lv.cpus = 2       # 2 CPUs for vault3 VM
    end
  end
end
